name: Optimize Images

on:
  pull_request:
    paths:
      - "apps/mooc/**/*.jpg"
      - "apps/mooc/**/*.jpeg"
      - "apps/mooc/**/*.png"
      - "apps/mooc/**/*.webp"

defaults:
  run:
    working-directory: ./2.1-setup

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          jpegProgressive: false
          pngQuality: "80"
          webpQuality: "80"
